services:
  postgres:
    image: postgres:15-alpine
    container_name: absequencealign-postgres-dev
    environment:
      POSTGRES_DB: absequencealign_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/backend/database/init:/docker-entrypoint-initdb.d
    command: >
      postgres
      -c shared_preload_libraries='uuid-ossp'
      -c log_statement=all
      -c log_min_duration_statement=0
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d absequencealign_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_test:
    image: postgres:15-alpine
    container_name: absequencealign-postgres-test
    environment:
      POSTGRES_DB: absequencealign_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5434:5432"  # Use different port to avoid conflict with postgres service
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    command: >
      postgres
      -c shared_preload_libraries='uuid-ossp'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d absequencealign_test"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  postgres_test_data:
