global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'absequencealign-backend'
    static_configs:
      - targets: ['backend:8000']
    scrape_interval: 30s
    metrics_path: '/metrics'

  - job_name: 'absequencealign-frontend'
    static_configs:
      - targets: ['frontend:80']
    scrape_interval: 30s
    metrics_path: '/health'
