name: AbSequenceAlign
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  # Bioinformatics tools
  - muscle
  - mafft
  - hmmer
  - anarci
  - clustalo
  - blast
  - igblast
  # Python packages
  - biopython
  - scipy
  - pandas
  - fastapi
  - uvicorn
  - pydantic
  - python-multipart
  - python-jose
  - passlib
  - python-dotenv
  - httpx
  - requests
  # Development tools
  - pytest
  - pytest-asyncio
  - pytest-cov
  - black
  - flake8
  - mypy
  - isort
  # System tools
  - git
  - curl
  # Additional production dependencies
  - gunicorn
  # Database dependencies
  - sqlalchemy
  - alembic
  - greenlet
  # Pip packages (not available in conda)
  - pip
  - pip:
      - git+https://github.com/oxpig/ANARCI.git
      - asyncpg==0.29.0
      - psycopg2-binary==2.9.9
      - click>=8.0.0
      - docker>=6.0.0
