name: AbSequenceAlign
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  # Bioinformatics tools
  - muscle
  - mafft
  - hmmer
  - anarci
  # Python packages
  - biopython
  - scipy
  - pandas
  - fastapi
  - uvicorn
  - pydantic
  - python-multipart
  - python-jose
  - passlib
  - python-dotenv
  - httpx
  - requests
  # Development tools
  - pytest
  - pytest-asyncio
  - pytest-cov
  - black
  - flake8
  - mypy
  - isort
  # System tools
  - git
  - curl
  # Additional production dependencies
  - gunicorn
  # Pip packages (not available in conda)
  - pip
  - pip:
      - git+https://github.com/oxpig/ANARCI.git
      - sqlalchemy==2.0.23
      - asyncpg==0.29.0
      - psycopg2-binary==2.9.9
      - alembic==1.13.1
      - greenlet==3.2.4
      - click>=8.0.0
